services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: lore-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Infrastructure/Migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lore-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  lore-network:
    driver: bridge